
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vira Meliana
 */
public class choiser extends javax.swing.JFrame {
 String uye, uyee;
    int z, pin = 1234, a = 3;
    int t, s, tab = 0;
    /**
     * Creates new form choiser
     */
    public choiser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        saldo = new javax.swing.JButton();
        Menabung = new javax.swing.JButton();
        Penarikan = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("David", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Silahkan Pilih Transaksi Anda");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 20, 550, 90);

        saldo.setBackground(new java.awt.Color(255, 255, 255));
        saldo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        saldo.setText("Cek Saldo");
        saldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saldoMouseClicked(evt);
            }
        });
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo);
        saldo.setBounds(90, 280, 140, 50);

        Menabung.setBackground(new java.awt.Color(255, 255, 255));
        Menabung.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Menabung.setText("Menabung");
        Menabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenabungActionPerformed(evt);
            }
        });
        getContentPane().add(Menabung);
        Menabung.setBounds(140, 180, 140, 50);

        Penarikan.setBackground(new java.awt.Color(255, 255, 255));
        Penarikan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Penarikan.setText("Penarikan");
        Penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenarikanActionPerformed(evt);
            }
        });
        getContentPane().add(Penarikan);
        Penarikan.setBounds(460, 180, 140, 50);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton4.setText("Info");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 280, 140, 50);

        exit.setBackground(new java.awt.Color(255, 51, 51));
        exit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(590, 410, 90, 50);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 130);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 710, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saldoMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        JOptionPane.showMessageDialog(null,"Saldo anda : " + tab); //informasi saldo
        z=JOptionPane.showConfirmDialog(null,"Transaksi lain ?","ATM Bersama",
            JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if (z==0)
        {
            this.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Terimakasih pengguna ATM Bersama,silahkan tunggu dan ambil karti ATM.");
            System.exit(0);
        }
    }//GEN-LAST:event_saldoMouseClicked

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_saldoActionPerformed

    private void MenabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenabungActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        uyee = JOptionPane.showInputDialog(null,"Jumlah Penyetoran atau Tabungan  : " ); //menabung
        s = Integer.parseInt(uyee);
        menabung hasil = new menabung();
        hasil.tabung(tab, s);
        tab =hasil.getsaldo();
        z=JOptionPane.showConfirmDialog(null,"Transaksi lain ?","ATM Bersama",
            JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if (z==0)
        {
            this.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Terimakasih pengguna ATM Bersama,silahkan tunggu dan ambil karti ATM.");
            System.exit(0);
        }
    }//GEN-LAST:event_MenabungActionPerformed

    private void PenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenarikanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        uyee = JOptionPane.showInputDialog(null,"Jumlah Penarikan : " ); //pengambilan
        t = Integer.parseInt(uyee);
        penarikan mengambil = new penarikan();
        mengambil.ambil(tab,t);
        tab =mengambil.getsaldo();
        z=JOptionPane.showConfirmDialog(null,"Transaksi lain ?","ATM Bersama",
            JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if (z==0)
        {
            this.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Terimakasih pengguna ATM Bersama,silahkan tunggu dan ambil karti ATM.");
            System.exit(0);
        }
    }//GEN-LAST:event_PenarikanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        z=JOptionPane.showConfirmDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n ","INFO",
            JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if (z==0)
        {
            this.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Terimakasih pengguna ATM Bersama,silahkan tunggu dan ambil kartu ATM.");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"SILAHKAN AMBIL KARTU ATM!","TERIMAKASIH",JOptionPane.WARNING_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choiser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menabung;
    private javax.swing.JButton Penarikan;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton saldo;
    // End of variables declaration//GEN-END:variables
}
